version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.14


    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # Build and tag the Docker image
      - run:
          name: Build and tag Docker image
          command: |
            docker build -t carlosvalentese/fpbasquet:$CIRCLE_BRANCH .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push carlosvalentese/fpbasquet:$CIRCLE_BRANCH


  lint:
    docker:
      - image: carlosvalentese/fpbasquet:$CIRCLE_BRANCH
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD


    steps:
      - checkout

      # Linter checks
      - run:
          name: Run linter checks
          command: |
            black --check .

  test:
    docker:
      - image: carlosvalentese/fpbasquet:$CIRCLE_BRANCH
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD


    steps:
      - checkout

      # Tests
      - run:
          name: Run tests
          command: |
            pytest

workflows:
  version: 2
  build-lint-test:
    jobs:
      - build
      - lint
      - test
